from enum import Enum

class PipelineState(str, Enum):
    DRAFT_CREATED = "DRAFT_CREATED"
    TOPIC_ANALYZED = "TOPIC_ANALYZED"
    RESEARCH_NOTES_READY = "RESEARCH_NOTES_READY"
    SCRIPT_READY = "SCRIPT_READY"
    SCENE_PLAN_READY = "SCENE_PLAN_READY"
    IMAGE_PROMPTS_READY = "IMAGE_PROMPTS_READY"
    VIDEO_PROMPTS_READY = "VIDEO_PROMPTS_READY"
    IMAGES_GENERATED = "IMAGES_GENERATED"
    CLIPS_GENERATED = "CLIPS_GENERATED"
    VOICEOVER_READY = "VOICEOVER_READY"
    SUBTITLES_READY = "SUBTITLES_READY"
    FINAL_RENDER_READY = "FINAL_RENDER_READY"
    FAILED = "FAILED"
